### ISSUE TITLE
Error running Docker Implementation

### ISSUE THREAD

**Issue by leldershaw** [jiujiezz/tsnad#24]
Error occurs when running TSNAD on matched tumour-normal WES samples, using the docker image.

**Command used (inside docker):**
python TSNAD.py -I samples/ -V grch38 -O results/

**Error message:**
[Tue Oct 06 00:50:29 UTC 2020] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 3.55 minutes.
Runtime.totalMemory()=13044285440
Tool returned:
0
Traceback (most recent call last):
  File "TSNAD.py", line 172, in <module>
    outputIndFiles = subfunction.runSAM(samtools_folder,gatk_tool,outputs_folder,outputSamFiles,typeNum,laneNum,threadNum);
  File "/home/tsnad/subfunction.py", line 180, in runSAM
    command4 = 'java -Xmx16g -jar' + ' ' + gatk_tool + ' MarkDuplicates -MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 8000 -I ' + outputMerge
Files[i] + ' -O ' + outputDedupFiles[i] + ' -M ' + outputDedupMetircs[i];
IndexError: list index out of range

**Comment by wujingcheng** [comment]
Could you provide more detailed information, please? Such as the file list in samples/, output file list in bwa_results/, samtools_results/, gatk_results/ and others.

**Comment by jiujiezz** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        应该是在github上的讨论区里面回复吧，邮件可能收不到
        
    
        
            
        
    
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.7;
        }
    

    
        font{
            line-height: 1.7;
        }
    
－－－－－－－－－－－－－－－－－－－Zhan Zhou, Ph.D.Associate ProfessorCollege of Pharmaceutical Sciences,Zhejiang UniversityHangzhou, China 310058Tel/Fax: +86-571-88208410Email: zhanzhou@zju.edu.cn



        
    
     

    On 10/6/2020 11:58，leldershaw<notifications@github.com> wrote： 



Error occurs when running TSNAD on matched tumour-normal WES samples, using the docker image.
Command used (inside docker):
python TSNAD.py -I samples/ -V grch38 -O results/
Error message:
[Tue Oct 06 00:50:29 UTC 2020] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 3.55 minutes.
Runtime.totalMemory()=13044285440
Tool returned:
0
Traceback (most recent call last):
File "TSNAD.py", line 172, in 
outputIndFiles = subfunction.runSAM(samtools_folder,gatk_tool,outputs_folder,outputSamFiles,typeNum,laneNum,threadNum);
File "/home/tsnad/subfunction.py", line 180, in runSAM
command4 = 'java -Xmx16g -jar' + ' ' + gatk_tool + ' MarkDuplicates -MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 8000 -I ' + outputMerge
Files[i] + ' -O ' + outputDedupFiles[i] + ' -M ' + outputDedupMetircs[i];
IndexError: list index out of range

**Comment by leldershaw** [comment]
Sure, here is some additional information.

**samples/** (input folder)
├── Mel5_PBMC_GATCAG_L008_R1_complete_filtered.fastq.gz
├── Mel5_PBMC_GATCAG_L008_R2_complete_filtered.fastq.gz
├── Mel5_tumor_CGATGT_L008_R1_complete_filtered.fastq.gz
└── Mel5_tumor_CGATGT_L008_R2_complete_filtered.fastq.gz
_0 directories, 4 files_

**results/** (output folder)
**├── bwa_results**
    └── Mel5.sam
**├── deephlapan_results
├── gatk_results
├── kourami_results
├── mutect2_results
├── samtools_results**
    ├── Mel5.bam
    ├── Mel5_sort.bam
    ├── Mel5_sort_dedup.bam
    ├── Mel5_sort_dedup.bam.bai
    └── Mel5_sort_dedup.metrics
**├── trimmomatic_results
└── vep_results**
_8 directories, 6 files_

**Comment by wujingcheng** [comment]
You can try to change the names of your input files as follows.
├── PBMC_Mel5_GATCAG_L008_R1_complete_filtered.fastq.gz
├── PBMC_Mel5_GATCAG_L008_R2_complete_filtered.fastq.gz
├── tumor_Mel5_CGATGT_L008_R1_complete_filtered.fastq.gz
└── tumor_Mel5_CGATGT_L008_R2_complete_filtered.fastq.gz

**Comment by leldershaw** [comment]
That worked! Thank you for your help.
